version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


#version: '3.9'
#
#services:
#  fastapi:
#    build: .
#    container_name: contacts_app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://postgres:19920716@db:5432/contacts_db
#    volumes:
#      - .:/app
#    restart: always
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#  db:
#    image: postgres:17
#    container_name: postgres_db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 19920716
#      POSTGRES_DB: contacts_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    restart: always
#
#volumes:
#  pg_data: